mysql:
  environment:
    - MYSQL_DATABASE=bonjourausy
    - MYSQL_ROOT_PASSWORD=admin
  image: 'bonjourausy_mysql:latest'
  volumes:
    - /var/lib/mysql
php:
  image: 'bonjourausy_app:latest'
  links:
    - mysql
  volumes:
    - ./images/app/src/public:/var/www/html
webnginx:
  image: 'bonjourausy_webnginx:latest'
  links:
    - php
  ports:
    - '8080:80'
  volumes_from:
    - php