<?php
	function verify_jwt_token($userId, $username, $password, $received_token) {
		// key for signature
		$key = "'".$userId."-".$username."-".$password."'";  

		// split a string by '.'
		$jwt_values = explode('.', $received_token);
		// extracting the signature from the original JWT
		$received_signature = $jwt_values[2];
		// concatenating the first two arguments of the $jwt_values array, representing the header and payload values
		$receivedHeaderAndPayload = $jwt_values[0].'.'.$jwt_values[1];
		// creating the Base64 encoded new signature generated by applying the HMAC method to the concatenated header and payload value
		$resultedSignature = base64_encode(hash_hmac('sha256', $receivedHeaderAndPayload, $key, true));

		// check if the created signature is equal to the received signature
		if($received_signature == $received_signature) {
			// If everything worked fine, if the signature is OK and the payload was not modified, you should get a success message
			// echo "Success";
			return true;
		}else{
			return false;
		}

	}
?>